import SwiftUI
import SkyBoundCore

struct SettingsScreen: View {
    @Environment(GameCoordinator.self) private var coordinator
    @State private var confirmReset = false

    var body: some View {
        let s = coordinator.player.profile.settings
        let version = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "1.0"
        GameScreen("Settings", kicker: "Pilot") {
            row("speaker.wave.2", "Sound effects", nil, binding(s.soundEnabled) { $0.soundEnabled = $1 })
            row("waveform", "Adaptive music", "Layers build with your combo", binding(s.musicEnabled) { $0.musicEnabled = $1 })
            row("iphone.radiowaves.left.and.right", "Haptics", nil, binding(s.hapticsEnabled) { $0.hapticsEnabled = $1 })
            row("waveform.path.ecg", "Screen shake", nil, binding(s.screenShakeEnabled) { $0.screenShakeEnabled = $1 })
            row("eye", "Path hint", "Marks the safe lane when yours is blocked", binding(s.ghostEnabled) { $0.ghostEnabled = $1 })

            SectionRule("About this build", trailing: "v\(version)").padding(.top, 8)
            VStack(alignment: .leading, spacing: 10) {
                Text("SkyBound is a prototype. Every coin, gem, storefront, pass, crate, duel, leaderboard and ad in it is simulated on this device. Nothing charges money and nothing leaves your phone.")
                Text("The concept, engine, obstacle patterns, UI and copy were generated by Claude, an AI assistant made by Anthropic.")
            }
            .font(.body(12.5))
            .foregroundStyle(Theme.muted)
            .lineSpacing(3)
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(.horizontal, 16).padding(.vertical, 14)
            .panel()

            Button {
                if confirmReset {
                    coordinator.resetProgress()
                } else {
                    confirmReset = true
                    coordinator.haptics.warning()
                }
            } label: {
                HStack {
                    Text(confirmReset ? "Tap again to confirm" : "Reset all progress")
                    Spacer()
                    Text(confirmReset ? "Wipes everything" : "Cannot be undone")
                        .font(.body(12, weight: .semibold)).tracking(0.7).textCase(.uppercase).foregroundStyle(Theme.muted)
                }
            }
            .buttonStyle(.outline(confirmReset ? Theme.flare : Theme.flareDeep, color: Theme.flare))
            .padding(.top, 10)
        }
    }

    private func row(_ icon: String, _ title: String, _ subtitle: String?, _ isOn: Binding<Bool>) -> some View {
        Toggle(isOn: isOn) {
            HStack(spacing: 12) {
                LineIcon(name: icon, size: 20, color: Theme.muted)
                VStack(alignment: .leading, spacing: 3) {
                    Text(title).font(.body(13.5, weight: .semibold)).foregroundStyle(Theme.text)
                    if let subtitle { Text(subtitle).font(.body(11.5)).foregroundStyle(Theme.muted) }
                }
            }
        }
        .toggleStyle(DeckToggleStyle())
        .padding(.horizontal, 14)
        .frame(height: subtitle == nil ? 52 : 60)
        .panel()
    }

    private func binding(_ value: Bool, _ set: @escaping (inout PlayerSettings, Bool) -> Void) -> Binding<Bool> {
        Binding(get: { value }, set: { new in coordinator.updateSettings { set(&$0, new) } })
    }
}
